@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhkIiwiZnVsbF9uYW1lIjoiRGFubnkiLCJlbWFpbCI6Imh1YW5nZG9uZ0BnbWFpbC5jb20iLCJ1c2VySWQiOjQ4LCJwaWN0dXJlIjpudWxsLCJpYXQiOjE3MzA2OTQwMTgsImV4cCI6MTczMTU1ODAxOH0.DyhGF5ne-plHAZV6-IO2g0CvsCG8uEjXoEW9BWdMe94

### GET /test it should return 404
GET {{host}}/ HTTP/1.1

### register

POST {{host}}/api/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "full_name": "testFull_name",
    "email" : "test@mail.com",
    "password" : "testpassword"   
}

### login
POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email" : "test@mail.com",
    "password" : "testpassword"   
}

### get user by id
GET {{host}}/api/users/48 HTTP/1.1


### create store

POST {{host}}/api/stores HTTP/1.1
Content-Type: application/json

{
    "country_id": 5,
    "name": "TestStore1",
    "description": "testDescription1",
    "user_id": 22
}

### get store for logged user
GET {{host}}/api/stores HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
# need to use actual token of the user existing in database, otherwise "Internal Server Error"

### get store by id
GET {{host}}/api/stores/35 HTTP/1.1

### GET payment intent
POST {{host}}/api/payments/create-payment-intent HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{"items":[{"id":"M4 MacBook Pro","amount":20000},{"id":"M1 MacBook Air","amount":10000}]}

### upload image
POST {{host}}/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="logo-image.png"
Content-Type: image/png

< ./logo-image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### get all countries

GET {{host}}/api/countries HTTP/1.1


### checkout
POST {{host}}/api/payments/checkout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{"paymentId": "pi_1J5J9vKXr6fXj5Z2J9J9J9J9"}
