@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJmdWxsX25hbWUiOiJ0ZXN0RnVsbF9uYW1lIiwiZW1haWwiOiJ0ZXN0QG1haWwuY29tIiwiaWF0IjoxNzMwNDcyNDQ1LCJleHAiOjE3MzkxMTI0NDV9.mg-9z1Sd0XMOwRLfUDYcSgaviwq4Eq5iZCCsJhRNvoU

### GET /test it should return 404
GET {{host}}/ HTTP/1.1

### register

POST {{host}}/api/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "full_name": "testFull_name",
    "email" : "test@mail.com",
    "password" : "testpassword"   
}

### login
POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email" : "test@mail.com",
    "password" : "testpassword"   
}

### create store

POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "country_id": 1,
    "name": "TestStore",
    "description": "testDescription",
    "user_id": 1
}

### GET payment intent
POST {{host}}/api/payments/create-payment-intent HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{"items":[{"id":"M4 MacBook Pro","amount":20000},{"id":"M1 MacBook Air","amount":10000}]}

### upload image
POST {{host}}/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="logo-image.png"
Content-Type: image/png

< ./logo-image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### get all countries

GET {{host}}/api/countries HTTP/1.1
